EcomerceEnv/Ecomerce/Ecomerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EcomerceEnv/Ecomerce/shop/urls.py
from .views import index,product_detail,add_to_cart
from django.urls import path

urlpatterns = [
    path("",index,name="product"),
    path("product/<int:id>",product_detail,name="product_detail"),
    path("add_to_cart/<int:id>",add_to_cart,name="add_to_cart")
]

EcomerceEnv/Ecomerce/shop/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    


class Product(models.Model):
    name=models.CharField(max_length=200)
    description=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    Category=models.ForeignKey(Category,related_name='product',on_delete=models.CASCADE)
    image=models.ImageField(upload_to="",null=True,blank=True)
    
    def __str__(self):
        return self.name
    
    
class Cart(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    product=models.ManyToManyField(Product,through="CartItem")
    
class CartItem(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return self.quantity
    
    
    
    

    

EcomerceEnv/Ecomerce/shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product,Cart,CartItem,Category
# Create your views here.

def index(request):
    product=Product.objects.all()
    return render(request,"index.html",{"product":product})



def product_detail(request,id):
    product=Product.objects.get(id=id)
    return render(request,"product_detail.html",{"product":product})


def add_to_cart(request,id):
    product=Product.objects.get(id=id)
    cart,created=Cart.objects.get_or_create(user=request.user)
    cart_item,created=CartItem.objects.get_or_create(cart=cart,product=product)
    if not created:
        cart_item.quantity+=1
        cart_item.save()
        return render(request,"cart.html",{"cart":cart})    
    return render(request,"cart.html",{"cart":cart})



    

EcomerceEnv/Ecomerce/shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title> {% block title %}{% endblock %} Shop</title>
</head>
<body>
    <!-- navbar code -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Cart</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#"}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Signup</a>
                </li>
                {% endif %}

    
           
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    <!-- end navbar code -->
   <div class="container mt-5">
    {% block content %}
    {% endblock %}
    
   </div>
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

EcomerceEnv/Ecomerce/shop/templates/cart.html
{% extends 'base.html' %}
{% block title %}Cart Page{% endblock %} 
{% block content %}
<h1>Shopping Cart</h1>
<div class="row">
    <div class="col-md-8">
        
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
                {% for item in cart.cartitem_set.all %}
              <tr>
                <td>{{item.product.name}}</td>
                <td>${{item.product.price}}</td>
                <td>{{item.quantity}}</td>
                <td>{{item.quantity| floatformat:2}}</td>
              </tr>
              {% endfor %}
              
              
            </tbody>
          </table>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title">Cart Summary</h5>
              {% for item in cart.cartitem_set.all %}
                <p class="card-text">{{item.product.price}} x {{item.quantity}}</p>
              {% endfor %}
              
                <h5>Total: ${{cart.total}}</h5>
              <a href="#" class="btn btn-success">Checkout</a>
            </div>
          </div>
    </div>
{% endblock content %}

EcomerceEnv/Ecomerce/shop/templates/index.html
{% extends 'base.html' %}
{% block title %}Product Page{% endblock %} 
{% block content %}
<h1>Products</h1>
<div class="row">
   {% for product in product %}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
               
                <p class="card-text"> {{ product.description|truncatechars:200 }}</p>
                <p class="card-text">{{ product.price }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'product_detail' product.id %}" class="btn btn-danger">View</a>
                        <a href="{% url 'add_to_cart' product.id %}" class="btn btn-success mx-3"> Add to Cart</a>
                    </div>
            </div>

   {% endfor %}
</div>
{% endblock %}

EcomerceEnv/Ecomerce/shop/templates/product_detail.html
{% extends 'base.html' %}
{% block title %}Product Detials Page{% endblock %} 
{% block content %}
<div class="row">
    <div class="col-md-6">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
    </div>
    <div class="col-md-6">
        <h1>{{product.name}}</h1>
        <p>{{product.description}}</p>
        <p>${{product.price}}</p>
        <a href="{% url 'add_to_cart' product.id %}" class="btn btn-success"> Add to Cart</a>
    </div>

    
</div>
{% endblock content %}